#!/bin/sh
#
# $Id: mkpksdconf.in,v 1.4 2002/09/29 20:05:18 rlaager Exp $
# 
# Copyright (c) 1996, 1997, 1998, 1999, Marc Horowitz.  All rights reserved.
# See the LICENSE file in the release for redistribution information.
#
# this script encodes some knowledge about the way autoconf behaves.
# in particular, it knows that prefix is an actual directory, and 
# exec_prefix and all the foodir variables are defined in terms of
# it.  I could have used sed in the Makefile, but that would duplicate
# code which mostly exists in configure.in, and is ugly.

prefix=/usr/local
exec_prefix=${prefix}

cat << EOF
pks_bin_dir ${exec_prefix}/bin
db_dir ${prefix}/var/db
www_dir ${prefix}/var
### Set www_port to the port on which HTTP requests should be accepted.
### If you do not want to process HTTP requests, set this to 0.
www_port 11371
### Set www_readonly to 0 if you want to allow ADD requests over HTTP
# www_readonly 0
socket_name ${prefix}/var/pksd_socket
### Specify the envelope sender address as the -f argument to
###   sendmail.  This is the address which will receive any bounces.
### If you don't use sendmail, then change this to an equivalent command.
### If you do not want to process mail requests, leave this unset.
mail_delivery_client /usr/sbin/sendmail -t -oi -fmailer-daemon
### Set this to the address which should be displayed as the From: 
###   address in all outgoing email, and as the maintainer in the body
###   of each message.
maintainer_email PGP Key Server Administrator <nobody>
mail_intro_file ${prefix}/share/mail_intro
help_dir ${prefix}/share
mail_dir ${prefix}/var/incoming
### If you change this, make sure to put a corresponding help file in
### the help_dir named above
default_language EN
### This is the email address of this site.  It will be inserted in all
###   outgoing incremental messages, so it should match whatever the
###   downstream sites use as syncsite in their pksd.conf files.
# this_site pgp-public-keys@your-site
### Include a syncsite line for each site with which you are exchanging
### incremental requests.
# syncsite pgp-public-keys@pgp-server-1
# syncsite pgp-public-keys@pgp-server-2
### Set this to 0 to disable mailserver LAST requests completely, to a
### positive integer to limit LAST requests to that many days, or -1
### to allow any argument to LAST.
# max_last -1
### Set this to the maximum number of keys to return in the reply to
### a last query.  Setting it to -1 will allow any size reply.
# max_last_reply_keys -1
### Set this to the maximum number of keys to return in the reply to
### an index, verbose index, or get query.  Setting it to -1
### will allow any size reply.
# max_reply_keys -1
EOF
